version: "1.0"
modules:
  - exclude_patterns:
      - "**/.git/**"
      - "**/node_modules/**"
      - "**/out/**"

      # Included in .gitignore:
      - "**/.vscode/**"
      - "**/.idea/**"
    exclude_scanners:
      - "iac"
      - "sast"
      - "secrets"
